### ISSUE TITLE
Suggestion for improvement : configuration

### ISSUE THREAD

**Issue by ghost** [jamielob/transitions#1]
Hello !
A good idea for this great plugin would be to allow the configuration of the name of the layout. In fact, I personally have several different layout, and I can not name them in the same ways ... Add a function to change the default layout, or even add multi-layout management would be interesting.
My best regards.

**Comment by jamielob** [comment]
Thanks for the suggestion, good idea and it's something that definitely needs to be added.  I've only just built this so please do install it and see if you can see any bugs.

**Comment by jamielob** [comment]
Container id and content class are now configurable and I've updated the readme accordingly.  Configuration is optional and the values default to #transitions-container and .transitions-content respectively.

**Comment by ghost** [comment]
Thank you very much ! ;) Reactive dev !
