### ISSUE TITLE
3d translate cause fixed elements to not remain fixed.

### ISSUE THREAD

**Issue by gamedolphin** [jamielob/transitions#12]
May be because of this [Chrome Issue](https://code.google.com/p/chromium/issues/detail?id=20574). I've commented the 3d translate part of [this file](https://github.com/jamielob/transitions/blob/master/transitions.js) and recompiled a custom plugin to get around this issue. 

Fixed nav bars and other such things do not remain fixed with these settings on.

**Comment by jamielob** [comment]
Thanks for this - do you have a demo of the problem you can post?

**Comment by gamedolphin** [comment]
I do not have public code to show this but you can test this easily by setting one or more elements of your template to fixed (along with a scrolling page). It does the same on firefox as well... seems to be that  the browsers are actually conforming to the W3C spec mentioned here - [W3C Spec](http://www.w3.org/TR/css3-2d-transforms/#transform-rendering) 

> In the HTML namespace, any value other than none for the transform results in the creation of both a stacking context and a containing block. The object acts as a containing block for fixed positioned descendants.

The above is from an [SO Answer](http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue).

I am guessing that the 3d translates are the ones that cause all the 3d transitions and hence we'll have to let go of all of them if we're using fixed elements.

**Comment by jamielob** [comment]
Interesting - I'll have a look when I have time.  Perhaps I'll need to add a "disable 3d" option.
