### ISSUE TITLE
How to slide in OnTop but not remove previous until done

### ISSUE THREAD

**Issue by kobescoresagain** [jamielob/transitions#13]
Hello,

Tried a few different things, not sure if it is possible.  I want to slide in from left on top (which I have working) but I want to do it over top of the previous page.  I don't want it to slide out.  How can I make that previous page not disappear until after the new page is slid all the way in.

**Comment by jamielob** [comment]
Hi @kobescoresagain.  You can use the delay class.  For example `data-transition-out="delay500"`
Available in 100 increments up to 1000.

**Comment by kobescoresagain** [comment]
@jamielob:  Here is what I did:  data-transition-out="delay500" data-transition-in="slideLeftIn onTop"  When I do that, I get a flash of the background after the slide in.  Is there a way to prevent that?

**Comment by jamielob** [comment]
How about with delay1000?  How does that affect the flash?

**Comment by kobescoresagain** [comment]
@jamielob no, I still get the flash.  It's not a white flash, it's the previous page that flashes overtop

**Comment by jamielob** [comment]
It sounds like some other CSS may be causing the previous page to pop back to it's starting position before being removed.  Can you recreate the problem in a demo repo?

**Comment by kobescoresagain** [comment]
Jamie,  I used an inspector  to modify
http://transitions-demo.meteor.com/

Changed the slide button to be: <a class="" data-transition-in="slideLeftIn onTop" data-transition-out="delay1000" href="/page2">Slide</a>

It slides over top, then the bottom pops over, then the slide over top page shows back up

**Comment by kobescoresagain** [comment]
I am using FF on a Mac.  Shows on Chrome in mac as well.

**Comment by kobescoresagain** [comment]
I got it working, I had to drop the delay down to a lower number and it removed the flash issue.

**Comment by jamielob** [comment]
Great! What was the number you had to use out of interest?

**Comment by kobescoresagain** [comment]
I had to use a 300.
