### ISSUE TITLE
CSS class names clashes with other frameworks

### ISSUE THREAD

**Issue by hyperborea** [jamielob/transitions#2]
I'm using semantic-ui which makes extensive use of the .content class. What do you think about namespacing the css selectors or at least make them configurable as suggested in issue #1?

PS: awesome package, looking forward to try it further.

**Comment by jamielob** [comment]
Thanks for taking a look! If I did make them configurable do you think I'd still need to namespace?  Or just perhaps make them #transitions-container and .transitions-content by default and then allow them to be changed.

**Comment by hyperborea** [comment]
Yeah I like that idea, "content" is a little too generic.

**Comment by jamielob** [comment]
Container id and content class are now configurable and I've updated the readme accordingly.  Configuration is optional and the values default to #transitions-container and .transitions-content respectively.
