### ISSUE TITLE
Errors while adding packages

### ISSUE THREAD

**Issue by mgarf** [jamielob/transitions#3]
Hi,

I am using the Windows RC version 1.1.0 and I tried install your plugin and received the following error 

 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint templating@1.1.0 is not satisfied by
templating 1.1.0-win.0.
Constraints on package "templating":
- templating@=1.1.0-win.0 <- top level
- templating@1.1.0-rc.0 <- meteor-platform 1.2.2-rc.0
- templating@1.1.0-rc.0 <- spacebars 1.0.6-rc.0 <- boilerplate-generator
  1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- autoupdate 1.2.0-win.0 <-
  meteor-platform 1.2.2-rc.0
- templating@1.1.0-rc.0 <- spacebars 1.0.6-rc.0 <- boilerplate-generator
  1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- iron:router 1.0.7
- templating@1.1.0-rc.0 <- spacebars 1.0.6-rc.0 <- meteor-platform
  1.2.2-rc.0
- templating@1.1.0-rc.0 <- launch-screen 1.0.2-rc.0 <- meteor-platform
  1.2.2-rc.0
- templating@1.0.6 <- iron:router 1.0.7
- templating@1.0.6 <- iron:layout 1.0.7 <- iron:controller 1.0.7 <-
  iron:router 1.0.7
- templating@1.0.6 <- iron:layout 1.0.7 <- iron:router 1.0.7
- templating@1.0.6 <- iron:dynamic-template 1.0.7 <- iron:controller 1.0.7
  <- iron:router 1.0.7
- templating@1.0.6 <- iron:controller 1.0.7 <- iron:router 1.0.7
- templating@1.0.4 <- joshowens:accounts-entry 1.0.3
- templating@1.0.4 <- joshowens:simple-form 0.2.2 <-
  joshowens:accounts-entry 1.0.3
- templating@1.0.4 <- schnie:uploader 2.0.3 <- joshowens:simple-form 0.2.2
  <- joshowens:accounts-entry 1.0.3
- templating@1.0.9 <- mrgalaxy:stripe 2.1.0
- templating@1.0.7 || 1.0.8 || 1.0.9 <- aldeed:autoform 4.2.2
- templating@1.0.0 <- aldeed:autoform-select2 2.0.1
- templating@1.0.9 <- aldeed:template-extension 3.4.3 <-
  aldeed:autoform-select2 2.0.1
- templating@1.0.9 <- multiply:iron-router-progress 1.0.1
- templating@1.0.9 <- buduguru:admin 1.1.6
- templating@1.0.8 || 1.0.9 <- aldeed:tabular 1.0.6 <- buduguru:admin
  1.1.6
- templating@1.1.0 <- jamielob:transitions 1.0.2

**Comment by jamielob** [comment]
Not sure why that's happening.  Can you try downloading the transitions package and placing it in a folder called `packages` inside your project.  So `/yourProjectFolder/packages/transitions/`.

Once you've done that run meteor `remove jamielob:transitions` and `meteor add jamielob:transitions`.

p.s. I haven't used the Windows install of Meteor and don't know how it differs so apologies if my instructions aren't clear for you.

**Comment by mgarf** [comment]
I put the package and editing the .version file to list the template version as 1.1.0.win.0. It successfully loaded in but I couldn't get the package to work afterwards. I found this page: https://github.com/meteor/meteor/wiki/Publishing-a-package-with-binary-dependencies-for-the-Windows-preview 

I don't know this applies to your package but could possibly compile it in a way that would make it work. I could test it if you like by forking. Please let me know.

**Comment by mgarf** [comment]
I created a fork, that I managed to get to work but I pulled up another error regarding undefined in onrender. I can't tell if its from the changes I made to the package or another error being thrown up. Can you give it a test on your system? meteor add mgarf:transitions

**Comment by jamielob** [comment]
Just removed mine and added your package into my demo suite locally and it seems to working fine without any errors.  What errors are you seeing?

**Comment by jamielob** [comment]
A good test would be to fork the demo suite and see if that runs ok for you, to rule out a conflict elsewhere - https://github.com/jamielob/transitions-demo

**Comment by mgarf** [comment]
So i took out the code from the package and placed it inside my own meteor client js and changed the Template.layout.render to Template.ApplicationLayout.OnRendered which is the template layout I assigned to my site. And Now the thing works :)

**Comment by jamielob** [comment]
Great! Looks like .OnRendered has replaced .rendered.  Let me do a quick test.

**Comment by jamielob** [comment]
I have updated the package to now user onRendered instead.  Looks like a couple of bits and pieces were deprecated that I hadn't realized.  You also highlighted that I had forgotten to put in the readme that the iron:router layout template has to be called 'template'.  Looks like I'll need to find a way to make that dynamic, which I'm not sure how to do currently.
