### ISSUE TITLE
Transition configuration on the Router

### ISSUE THREAD

**Issue by joshua1** [jamielob/transitions#4]
Hi @jamielob is there a provision for configuring data-transition-out and data-transition-in on the router config. It should be possible to want a single in and out transition for all pages rendered inside the "yield" container. One would only have to add data-transition-out and data-transition-in in links where we need a different transition style for.

**Comment by jamielob** [comment]
Hi @joshua1.  I've been working on a major update to the package that adds the capability to do inline transitions as well as full page ones.  I'll implement a default in and out transitions feature too.

**Comment by jamielob** [comment]
Just published version 2.0.0 which includes the default transition functionality.

**Comment by joshua1** [comment]
great @jamielob thanks
