### ISSUE TITLE
Error if no template named "layout"

### ISSUE THREAD

**Issue by schnie** [jamielob/transitions#5]
Getting an `Error: Cannot read property 'events' of undefined`, if I don't have a template named `layout`.  Possibly declare those click handlers using regular old jquery, rather than to a template?

**Comment by jamielob** [comment]
Oops, that's left over from version 1! I'll fix that now.

**Comment by schnie** [comment]
Was gonna send a PR, but something happened and the commit was ugly.  Here's what I used:

```
$(document)
  .on('click', '[data-transition-in]', function(event) {
    transitionIn = $(event.currentTarget).data('transition-in');
  })
  .on('click', '[data-transition-out]', function(event) {
    transitionOut = $(event.currentTarget).data('transition-out');
  });
```

**Comment by jamielob** [comment]
Perfect! Added.
