### ISSUE TITLE
How to achieve slide-over effect?

### ISSUE THREAD

**Issue by ThaumRystra** [jamielob/transitions#8]
I'd like to achieve a slider over effect, where the outbound page stays where it is and the new page slides in over it, but I can't figure out how to do it.

Unsetting `data-transition-out` just causes the outbound page to disappear immediately, unlike unsetting `data-transition-in` which causes the incoming page to appear immediately and stay. This behaviour makes sense, since if both are unset, it should just be a jump between the two pages with no transition.

Is there a way of achieving what I'm after currently? If not this is a feature request for `data-transition-out="stay"` to be a thing.

**Comment by jamielob** [comment]
Hi Stefan,

I'm out of the office with no wifi at the moment.  It should be possible with a combination of the delay and onTop classes. I'll be able to check and provide an example once I'm back.

Jamie

**Comment by ThaumRystra** [comment]
That was enough of a hint, I didn't think to use delay on its own, got it working with `data-transition-out="delay500" data-transition-in="slideRightIn onTop"`

Thanks!

**Comment by jamielob** [comment]
Great! Good work.
